name: MetadataTestsPipeline

on:
  schedule:
    - cron: '0 15 30 * *' # run at 2 AM UTC

jobs:
  Linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Run Tests
        run: mvn test